### PR TITLE
added simple chinese i18n file

### PR DESCRIPTION
**Pull request by ButterflyTech**
## Connection with issue(s)

Resolve issue: null

Connected to: null

## Screenshots or Videos

image
image
image

## To Do

- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by jesusrp98** [comment]
Thank you very much to take the time to translate the app!! I really appreciate.

Did you revise all of the screens to see if there's any problem?
As far as I can see, there aren't any UI issues related to languages, and since I don't speak Chinese I can't  ://

If there's anything I can help you let me know!! Once again, thank you very much, this feature is HUGE!!

**Comment by ButterflyTech** [comment]
> Thank you very much to take the time to translate the app!! I really appreciate.
> 
> Did you revise all of the screens to see if there's any problem?
> As far as I can see, there aren't any UI issues related to languages, and since I don't speak Chinese I can't ://
> 
> If there's anything I can help you let me know!! Once again, thank you very much, this feature is HUGE!!

I have reviewed all screens, and no problem found. this is amazing  app with nice design,  so I'm glad to translate it.

**Comment by jesusrp98** [comment]
Thank you very much for your support!
This project wouldn't be possible with all the support of the community, including you!

Also, a couple things before pulling your translations:
1. Under the 'Translators' menu inside the About page, how could I refer to you? Also, just to be clear, the language name is 'Simplified Chinese' right?
2. In case I add new features down the road that need to be translated, would you be available to translate a couple of strings? In that case, contact me via [this email](mailto:spacex.go.app@gmail.com).

**Comment by ButterflyTech** [comment]
Q1: You can call me 'loopsun', and you are right, the language name is 'Simplified Chinese'.

Q2: I am happy to continue to contribute this project，if you added new features, I will update the translation file soon.

**Comment by jesusrp98** [comment]
Merging it to the dev branch, thanks!
This new feature will be available in the next v2.8 update, which will be ready by the end of October!

**Pull request merged**
