### PR TITLE
Enable lint in this project

### PR DESCRIPTION
**Pull request by passsy**
## Description

Enables [lint](https://pub.dev/packages/lint) in this project to catch bugs early.
Most warnings are directly applied.

I haven't fixed all issues. The const constructor lint rule requires Dart 2.5/Flutter 1.9. And this project seems to run with all flutter versions. I don't feel comfortable lifting the SDK myself.

## Testing and Review Notes

Run `flutter analyze` to see the remaining issues. Or look into the Analyzer tab in VScode/IntelliJ

### CODE REVIEW

**Comment by jesusrp98** [comment]
First, I wanted to say thank you very much for taking the time to fix those style issues.

Secondly, I've been doing some changes in the `dev` branch, and pulling this into `master`directly may cause some issues in the future.

Do you mind if you pull these changes to the `dev` branch?
Did you carry out those changes in the code by hand, or do you have a tool to do that automatically? I'd be really interesting in such a tool.

I also checked that you're the developer behind the `lint` package: congratulations, it's great! I'm going to implement this kind of style checking to all my project.

**Comment by passsy** [comment]
I totally missed the `dev` branch. I'll move the changes to there.

While some lint warning can be solved automatically, most changes here require manual adjustments

**Comment by jesusrp98** [comment]
Great! Maybe I could help you implement those styles changes to `dev` :)

**Comment by passsy** [comment]
Close in favour of #61

**Pull request closed without merging**
