### PR TITLE
WIP German translations

### PR DESCRIPTION
**Pull request by m0veax**
Adding missing German translations. This is still WIP. I will leave a note after i finished translating the App :)

## To Do

- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] request the "UX" team perform a design review (if/when applicable)

### CODE REVIEW

**Comment by jesusrp98** [comment]
Hey @m0veax, thank you very much for supporting this project, translating it to German. I've always wanted to translate this app to German, since I have a decent level of understanding of that language, but never had the time to do that.

Once you complete the translation process, I'd more than gladly update the update to the store. Let me know if you need anything from me!

**Comment by jesusrp98** [comment]
Any news related to thus PR @m0veax ?

**Comment by m0veax** [comment]
Yeah, I get a lot of 404s when I try to enter screens with images in the avd emulator.

Currently I'm trying to figure out if that happens because my corporate connection.

Did you ever experienced something like this?

**Comment by jesusrp98** [comment]
No, there are a couple broken image URLs broken within the services. It'll be fixed in the coming days.

If you're issues running the app, just launch it through the terminal:
`flutter run`

The app wouldn't stop for every 404 it founds @m0veax  :)

**Comment by m0veax** [comment]
My vacation ends next week.

I will be on my computer's again after that. I tend to not use them, otherwise I'll not have a healthy vacation

**Comment by jesusrp98** [comment]
Yeah! No problem. Just let me now when the translation process is done :)
Thanks!

**Comment by jesusrp98** [comment]
Hey, any updated? @m0veax

**Comment by m0veax** [comment]
Hey,

sry. Everytime i come back to this project, i have to fight another Issue.

This time, i have some kotlin related problems:

```
> flutter run

Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':launch_review'.
> Could not resolve all artifacts for configuration ':launch_review:classpath'.
   > Could not download kotlin-stdlib-jre8.jar (org.jetbrains.kotlin:kotlin-stdlib-jre8:1.2.0)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.0/kotlin-stdlib-jre8-1.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.2.0/kotlin-stdlib-jre8-1.2.0.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download kotlin-stdlib-jre7.jar (org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.0)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.2.0/kotlin-stdlib-jre7-1.2.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.2.0/kotlin-stdlib-jre7-1.2.0.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.2.20)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.20/kotlin-stdlib-1.2.20.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.20/kotlin-stdlib-1.2.20.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> Could not get unknown property 'android' for project ':launch_review' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         6,1s
Exception: Gradle task assembleDebug failed with exit code 1

```

I have added the last translation Strings, but i can't try it right now.

You said, you understand some german? Could you try it out and give me a screenshot if something is missing? 

I really want to finish this :)

**Comment by jesusrp98** [comment]
I'll try to make this PR ready to merge.
Thanks for all your hard work!

**Comment by jesusrp98** [comment]
It should be all fixed now.
I'll merge now and check if there's anything wrong.

Once again, thanks for all your hard work!

**Comment by m0veax** [comment]
Appreciate!

Thanks for building this app, I use it on a regular base and will be happy if it is available in german too.

I'll try your fixes right now.

**Comment by m0veax** [comment]
> It should be all fixed now.
> I'll merge now and check if there's anything wrong.
> 
> Once again, thanks for all your hard work!

Well, this did not solved my kotlin plugin problems. I guess that this is something in my Android Studio Setup i need to investigate.

But it only happens in this project.

If you find some issues, just drop me a message :)

**Pull request merged**
