### PR TITLE
Update es.json

### PR DESCRIPTION
**Pull request by jjoselv**
Minor corrections

### CODE REVIEW

**Comment by jesusrp98** [comment]
Thank you for taking the time to fix some translations issues.
Please, could you explain the motivation behind these changes? I see that the second change, related to the word 'captura' is a typo, but I don't understand the other changes.

**Comment by jjoselv** [comment]
Hello! Sure, let me explain. Solo does not have a mandatory accent (purely cosmetic) and I thought that to call machine's legs "piernas" is not very correct IMHO. The last change, the closing braces, I have no idea, maybe line termination or whitespace mishap?

**Comment by jesusrp98** [comment]
I get changing 'Piernas de aterrizaje' to 'Patas de aterrizaje', and I think it's a great change, but I think I'd have 'Sólo' rather than 'Solo', the accent emphasizes the word. 
Would you mind roll it back to 'Sólo'?

**Comment by jjoselv** [comment]
Sure!

**Comment by jjoselv** [comment]
Done!

**Comment by jesusrp98** [comment]
Thank you very much for your dedication.
If you find something else that need some refinement, let me know :)

**Pull request merged**
