### PR TITLE
Enable lint for dev branch

### PR DESCRIPTION
**Pull request by passsy**
## Description

Enables [lint](https://pub.dev/packages/lint) in this project to catch bugs early.
Most warnings are directly applied.

2nd attempt, this time for the `dev` branch.

## Testing and Review Notes

All issues are fixed or ignored. The issues which can only be solved with Flutter 1.9 are marked with a TODO.

### CODE REVIEW

**Comment by jesusrp98** [comment]
Thank you once again to take the time to apply some style fixes to this project.

I wanted you to ask if you could allowed me to upload changes to the `passy/spacex-go` repo, in order to include further modifications.

Thanks

**Comment by passsy** [comment]
"Allow edits from maintaines" is enabled
Screen-Shot-2019-09-18-18-25-50 18

**Comment by jesusrp98** [comment]
Ah, I'm sorry hahahaa.

The only ones left are `prefer_const_constructors`.
I also updated the project to support Flutter 1.9.

**Comment by jesusrp98** [comment]
The only one I'd like to fix is the `mismatched_getter_and_setter_types` hint inside the `app_model.dart` file.

**Comment by jesusrp98** [comment]
Finally merging this to the `dev` branch.

Thank you very much!

**Pull request merged**
