### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by caercam**

### CODE REVIEW

**Comment by jesusrp98** [comment]
Thank you very much for taking the time to do the French translations. This project is the product of all the community, collaborating together to build the best SpaceX mobile experience: it really really means a lot to me :)

In case I add new features down the road that need to be translated, would you be available to translate a couple of strings? In that case, contact me via this (email)[spacex.go.app@gmail.com].

Also, I've swapped the `master` branch for the `dev` one, since is where I usually add all changes in development.

Planning to merge it once I take a deeper look at the changes, hopefully in a couple hours.

**Comment by ButterflyTech** [comment]
> _No description provided._

welcome

**Comment by jesusrp98** [comment]
@CaerCam there's a missing translation still:
- "Upcoming launches" in the line 270.

Everything else is correct. Great job!!

**Comment by caercam** [comment]
Can't edit myself right now, translation is "Prochains lancements" :)

**Comment by jesusrp98** [comment]
Great, going to edit it and merge the result.

Once again, thank you very much for your great job!!

**Pull request merged**
