### PR TITLE
Adding browser selection in settings page

### PR DESCRIPTION
**Pull request by jesusrp98**
Implementing a Cubit that controls the type of browser where open URL to.

### CODE REVIEW

**Comment by jesusrp98** [comment]
@m0veax The cubit has already been implemented, as well as some testing of the component.
The only thing left would be to update the `openURL` function itself to add the selection logic itself :)

Let me know if you some help there.

**Comment by m0veax** [comment]
Hey,

thanks for your work. I will have a look at it next week

**Comment by m0veax** [comment]
Seems like my UI changes didn't survive. I will try to recover them through my local repository

**Comment by jesusrp98** [comment]
Yes, I forgot about that. You could copy what you did on the other branch if you want to :)

**Comment by m0veax** [comment]
Hey @jesusrp98,

i've reimplemented the UI and followed the code for ImageQuality settings. I added german and english translations and tested it in an AVD Emulator and on a Zebra Device.

Out of my POV the feature is working. Could you take a look and check if you need any changes?

#116 should be solved with this PR.

**Comment by jesusrp98** [comment]
Really great job @m0veax!
I've done some modifications to the visual aspect, updating some translations, as well as adding spanish ones too!

Could you please update the german translations to match the english ones? Thanks.

After that, I'll merge this to the origianl master, and publish the changes this weekend!

**Comment by m0veax** [comment]
Hey @jesusrp98, thanks for your changes. That really looks better :)

I updated the german translation to match the english ones. Can't wait to see the changes published :)

BTW: I added the repository to my Watchlist and will help out if I find another issue where i see a solution

**Comment by jesusrp98** [comment]
@m0veax Nice! Thank you very much for your support!

**Pull request merged**
